// Plugin thermal-power-600 — alarm KHAI BÁO đã rationalize (doc 08). Dữ liệu thuần: CHỈ import type
// từ @idtp/sdk. Alarm Engine chạy state machine. Setpoint neo Design Basis (Phụ lục A §3); ngoài đó
// gắn [GIẢ ĐỊNH] (doc 25). Deadband + on/off delay bắt buộc (chống chattering, EEMUA 191).
// Đây là subset Boiler Island; roll-up đầy đủ ~650 alarm ở doc 08 §5.
import type { AlarmDef } from '@idtp/sdk';

export const boilerAlarms: ReadonlyArray<AlarmDef> = [
  // --- Drum level (LT-001), trip ±250 mm (Design Basis §3.2) ---
  {
    alarmId: 'BLR-DRUM-LVL-HH',
    tagId: 'BLR_DRUM_LEVEL_01',
    condition: 'HH',
    priority: 'P1',
    setpoint: 250,
    deadband: 5,
    onDelayMs: 2000,
    offDelayMs: 8000,
    suppressWhen: 'unit_state == SHUTDOWN',
    consequence: { vi: 'Bao hơi quá cao → cuốn nước sang turbine', en: 'Drum HH -> water carryover to turbine' },
    corrective: { vi: 'Giảm cấp nước; kiểm 3-element', en: 'Reduce feedwater; check 3-element' },
  },
  {
    alarmId: 'BLR-DRUM-LVL-LL',
    tagId: 'BLR_DRUM_LEVEL_01',
    condition: 'LL',
    priority: 'P1',
    setpoint: -250,
    deadband: 5,
    onDelayMs: 2000,
    offDelayMs: 8000,
    suppressWhen: 'unit_state == SHUTDOWN',
    consequence: { vi: 'Cạn nước lò → MFT bảo vệ', en: 'Low drum -> protective MFT' },
    corrective: { vi: 'Tăng cấp nước; kiểm BFP', en: 'Increase feedwater; check BFP' },
  },
  {
    alarmId: 'BLR-DRUM-LVL-HI',
    tagId: 'BLR_DRUM_LEVEL_01',
    condition: 'H',
    priority: 'P2',
    setpoint: 50,
    deadband: 5,
    onDelayMs: 3000,
    offDelayMs: 8000,
    consequence: { vi: 'Mức bao hơi cao bất thường', en: 'Abnormally high drum level' },
  },
  {
    alarmId: 'BLR-DRUM-LVL-LO',
    tagId: 'BLR_DRUM_LEVEL_01',
    condition: 'L',
    priority: 'P2',
    setpoint: -50,
    deadband: 5,
    onDelayMs: 3000,
    offDelayMs: 8000,
    consequence: { vi: 'Mức bao hơi thấp bất thường', en: 'Abnormally low drum level' },
  },
  // --- Main steam pressure (17,5 MPa danh định) ---
  {
    alarmId: 'BLR-MSTM-PRESS-HH',
    tagId: 'BLR_MSTM_SH_PRESS_01',
    condition: 'HH',
    priority: 'P1',
    setpoint: 19.3, // [GIẢ ĐỊNH] ~ +10% trên danh định → PSV nguy cơ
    deadband: 0.1,
    onDelayMs: 2000,
    offDelayMs: 8000,
    consequence: { vi: 'Áp hơi quá cao → mở van an toàn', en: 'Steam HH -> safety valve lift' },
    corrective: { vi: 'Giảm firing; kiểm turbine bypass', en: 'Reduce firing; check turbine bypass' },
  },
  {
    alarmId: 'BLR-MSTM-PRESS-LO',
    tagId: 'BLR_MSTM_SH_PRESS_01',
    condition: 'L',
    priority: 'P2',
    setpoint: 16.0, // [GIẢ ĐỊNH]
    deadband: 0.1,
    onDelayMs: 3000,
    offDelayMs: 8000,
    consequence: { vi: 'Áp hơi thấp → mất phối hợp lò-turbine', en: 'Low steam pressure -> CCS mismatch' },
  },
  // --- SH steam temp (541 °C danh định) ---
  {
    alarmId: 'BLR-MSTM-TEMP-HH',
    tagId: 'BLR_MSTM_SH_TEMP_01',
    condition: 'HH',
    priority: 'P2',
    setpoint: 551, // [GIẢ ĐỊNH] +10 °C → nguy cơ quá nhiệt ống góp
    deadband: 2,
    onDelayMs: 3000,
    offDelayMs: 10000,
    consequence: { vi: 'Quá nhiệt hơi SH → hại ống góp/turbine', en: 'SH overtemp -> header/turbine damage' },
    corrective: { vi: 'Tăng spray attemperator; giảm tải', en: 'Increase spray; reduce load' },
  },
  // --- Flue O2 (3,2% danh định) ---
  {
    alarmId: 'BLR-FLUE-O2-LO',
    tagId: 'BLR_FLUE_O2_01',
    condition: 'L',
    priority: 'P2',
    setpoint: 1.5, // [GIẢ ĐỊNH] cháy thiếu gió → CO cao, nguy cơ nổ
    deadband: 0.2,
    onDelayMs: 5000,
    offDelayMs: 10000,
    consequence: { vi: 'Thiếu gió → cháy không hết, CO cao', en: 'Low O2 -> incomplete combustion, high CO' },
    corrective: { vi: 'Tăng gió (FD damper); kiểm air/fuel', en: 'Increase air; check air/fuel ratio' },
  },
  // --- Furnace pressure/draft (−50 Pa, dải −200…+200) ---
  {
    alarmId: 'BLR-FURN-PRESS-HH',
    tagId: 'BLR_FURN_PRESS_01',
    condition: 'HH',
    priority: 'P1',
    setpoint: 200,
    deadband: 10,
    onDelayMs: 1000,
    offDelayMs: 5000,
    consequence: { vi: 'Áp buồng lửa dương cao → phụt lửa/nổ', en: 'Furnace HH -> flame-out/explosion risk' },
    corrective: { vi: 'Kiểm ID/FD; runback nếu cần', en: 'Check ID/FD fans; runback if needed' },
  },
  {
    alarmId: 'BLR-FURN-PRESS-LL',
    tagId: 'BLR_FURN_PRESS_01',
    condition: 'LL',
    priority: 'P1',
    setpoint: -200,
    deadband: 10,
    onDelayMs: 1000,
    offDelayMs: 5000,
    consequence: { vi: 'Áp buồng lửa âm sâu → móp lò (implosion)', en: 'Furnace LL -> furnace implosion' },
    corrective: { vi: 'Kiểm ID fan; runback', en: 'Check ID fan; runback' },
  },
  // --- Soot blower (thổi bụi bề mặt truyền nhiệt, doc 10 §10 BOP) — ngưỡng ngoài dải vận hành thường ---
  {
    alarmId: 'SB-FOULING-HI',
    tagId: 'SB_FOULING_INDEX_01',
    condition: 'H',
    priority: 'P3',
    setpoint: 55,
    deadband: 2,
    onDelayMs: 5000,
    offDelayMs: 10000,
    consequence: { vi: 'Bám bề mặt cao → khói ra nóng, hiệu suất lò giảm', en: 'High fouling -> hot flue gas, boiler efficiency loss' },
    corrective: { vi: 'Khởi động chu trình thổi bụi; kiểm máy thổi kẹt', en: 'Start soot-blowing cycle; check stuck blowers' },
  },
  {
    alarmId: 'SB-STEAM-PRESS-LO',
    tagId: 'SB_STEAM_HEADER_PRESS_01',
    condition: 'L',
    priority: 'P2',
    setpoint: 20,
    deadband: 1,
    onDelayMs: 3000,
    offDelayMs: 5000,
    consequence: { vi: 'Áp hơi thổi thấp → thổi bụi không hiệu quả', en: 'Low blowing-steam pressure -> ineffective soot blowing' },
    corrective: { vi: 'Kiểm van cấp hơi header thổi bụi; hoãn chu trình', en: 'Check blowing-steam supply valve; defer cycle' },
  },
  // ── BoP "6+1" rationalization (doc 08 §5.1) — nâng điều kiện malfunction BoP thành AlarmDef first-class,
  // đủ deadband + on/off delay + suppression (§1–§3). Setpoint neo giữa giá trị NORMAL và FAULTED đã đo. ──
  {
    alarmId: 'WTP-DM-COND-HI',
    tagId: 'WT_PRODUCT_COND_01',
    condition: 'H',
    priority: 'P2',
    setpoint: 0.2, // µS/cm — breakthrough (normal 0,08 · rò nhựa 0,60)
    deadband: 0.03,
    onDelayMs: 5000,
    offDelayMs: 10000,
    consequence: { vi: 'Nước DM nhiễm bẩn → tạp chất vào chu trình, ăn mòn/bám cặn', en: 'DM water contamination -> cycle impurity ingress, corrosion/scaling' },
    corrective: { vi: 'Chuyển train DM dự phòng; tái sinh/thay nhựa', en: 'Switch to standby DM train; regenerate/replace resin' },
  },
  {
    alarmId: 'EMG-STATION-BLACKOUT',
    tagId: 'UPS_ON_BATTERY_01',
    condition: 'H',
    priority: 'P1',
    setpoint: 0.5, // cờ 0/1 — UPS chạy ắc-quy (mất nguồn tự dùng)
    deadband: 0.1,
    onDelayMs: 2000,
    offDelayMs: 5000,
    consequence: { vi: 'Mất nguồn tự dùng → tải quan trọng chạy ắc-quy có hạn; cần EDG', en: 'Station blackout -> critical loads on finite battery; needs EDG' },
    corrective: { vi: 'Xác nhận EDG khởi động & mang tải; giảm tải không thiết yếu', en: 'Confirm EDG start & loading; shed non-essential loads' },
  },
  {
    alarmId: 'SWY-LINE-TRIP',
    tagId: 'SY_LINES_INSERVICE_01',
    condition: 'L',
    priority: 'P2',
    setpoint: 1.5, // < 2 đường trong vận hành → 1 đường 500 kV bị cắt
    deadband: 0.1,
    onDelayMs: 2000,
    offDelayMs: 5000,
    consequence: { vi: 'Cắt 1 đường 500 kV → đường còn lại quá tải (dòng ×2)', en: 'One 500 kV line tripped -> remaining line overload (current x2)' },
    corrective: { vi: 'Kiểm bảo vệ đường dây; giảm phát nếu quá tải kéo dài', en: 'Check line protection; reduce generation if overload persists' },
  },
  {
    alarmId: 'HVAC-CR-TEMP-HI',
    tagId: 'HVAC_CR_TEMP_01',
    condition: 'H',
    priority: 'P2',
    setpoint: 24.5, // °C — phòng điều khiển (normal 23 · mất chiller tăng dần)
    deadband: 0.3,
    onDelayMs: 5000,
    offDelayMs: 10000,
    consequence: { vi: 'Mất làm mát → nhiệt phòng ĐK & tủ điện tăng, nguy cơ quá nhiệt thiết bị', en: 'Cooling loss -> control room & switchgear temp rise, equipment overheat risk' },
    corrective: { vi: 'Khởi động chiller dự phòng; kiểm bơm CHW', en: 'Start standby chiller; check CHW pump' },
  },
  {
    alarmId: 'FIRE-DETECTED',
    tagId: 'FIRE_ALARM_ACTIVE_01',
    condition: 'H',
    priority: 'P1',
    setpoint: 0.5, // cờ 0/1 — báo cháy vùng
    deadband: 0.1,
    onDelayMs: 1000,
    offDelayMs: 5000,
    consequence: { vi: 'Cháy → nguy hiểm người & thiết bị; bơm chữa cháy chính chạy, rút bồn', en: 'Fire -> personnel & equipment hazard; main pump runs, tank drawdown' },
    corrective: { vi: 'Xác nhận vùng cháy theo SOP PCCC; triển khai ứng phó', en: 'Confirm fire zone per fire SOP; deploy response' },
  },
  {
    alarmId: 'CHEM-FW-PH-LO',
    tagId: 'CHEM_FW_PH_01',
    condition: 'L',
    priority: 'P2',
    setpoint: 8.8, // pH — vùng ăn mòn (normal 9,30 · mất điều hoá 8,40)
    deadband: 0.1,
    onDelayMs: 5000,
    offDelayMs: 10000,
    consequence: { vi: 'Mất điều hoá hoá chất → pH vùng ăn mòn, độ dẫn cation tăng → ăn mòn chu trình', en: 'Dosing loss -> corrosive pH, cation conductivity rise -> cycle corrosion' },
    corrective: { vi: 'Kiểm bơm định lượng amoniac/hydrazine; phục hồi điều hoá', en: 'Check ammonia/hydrazine dosing pumps; restore conditioning' },
  },
  {
    alarmId: 'CA-IA-PRESS-LO',
    tagId: 'CA_IA_HEADER_PRESS_01',
    condition: 'L',
    priority: 'P1',
    setpoint: 5.5, // barg — header khí điều khiển (normal ~7,2 · mất khí nén tụt về sàn 5,3)
    deadband: 0.2,
    onDelayMs: 2000,
    offDelayMs: 5000,
    consequence: { vi: 'Mất khí điều khiển → van khí về vị trí fail-safe, mất điều khiển thiết bị', en: 'Instrument-air loss -> valves to fail-safe, loss of device control' },
    corrective: { vi: 'Khởi động máy nén dự phòng; cô lập rò; kiểm bình chứa', en: 'Start standby compressor; isolate leak; check receiver' },
  },
];
