// Plugin water-treatment-demo — 8 alarm KHAI BÁO (ISA-18.2). Chỉ import type từ @idtp/sdk. Cùng
// AlarmEngine generic chạy — không sửa engine. Setpoint demo [GIẢ ĐỊNH]. Đủ deadband + delay (EEMUA 191).
import type { AlarmDef } from '@idtp/sdk';

export const waterAlarms: ReadonlyArray<AlarmDef> = [
  {
    alarmId: 'WTP-TANK-LVL-HH',
    tagId: 'WTP_TANK_LEVEL_01',
    condition: 'HH',
    priority: 'P1',
    setpoint: 90,
    deadband: 2,
    onDelayMs: 3000,
    offDelayMs: 8000,
    consequence: { vi: 'Bể tràn', en: 'Tank overflow' },
    corrective: { vi: 'Giảm cấp; kiểm van', en: 'Reduce feed; check valve' },
  },
  {
    alarmId: 'WTP-TANK-LVL-HI',
    tagId: 'WTP_TANK_LEVEL_01',
    condition: 'H',
    priority: 'P2',
    setpoint: 80,
    deadband: 2,
    onDelayMs: 4000,
    offDelayMs: 8000,
    consequence: { vi: 'Mức cao', en: 'High level' },
  },
  {
    alarmId: 'WTP-TANK-LVL-LO',
    tagId: 'WTP_TANK_LEVEL_01',
    condition: 'L',
    priority: 'P2',
    setpoint: 25,
    deadband: 2,
    onDelayMs: 4000,
    offDelayMs: 8000,
    consequence: { vi: 'Mức thấp → nguy cơ cạn cấp nước lò', en: 'Low level -> risk to boiler makeup' },
  },
  {
    alarmId: 'WTP-TANK-LVL-LL',
    tagId: 'WTP_TANK_LEVEL_01',
    condition: 'LL',
    priority: 'P1',
    setpoint: 10,
    deadband: 2,
    onDelayMs: 2000,
    offDelayMs: 8000,
    consequence: { vi: 'Cạn bể → mất cấp nước DM', en: 'Tank empty -> loss of DM supply' },
    corrective: { vi: 'Khởi động bơm dự phòng', en: 'Start standby pump' },
  },
  {
    alarmId: 'WTP-FEED-FLOW-LO',
    tagId: 'WTP_FEED_FLOW_01',
    condition: 'L',
    priority: 'P2',
    setpoint: 5,
    deadband: 2,
    onDelayMs: 5000,
    offDelayMs: 10000,
    consequence: { vi: 'Mất lưu lượng cấp', en: 'Loss of feed flow' },
  },
  {
    alarmId: 'WTP-PUMP-A-TRIP',
    tagId: 'WTP_PUMP_A_RUN',
    condition: 'L',
    priority: 'P1',
    setpoint: 0.5,
    deadband: 0.1,
    onDelayMs: 1000,
    offDelayMs: 2000,
    consequence: { vi: 'Bơm cấp A dừng', en: 'Feed pump A tripped' },
    corrective: { vi: 'Chuyển bơm B; kiểm bơm A', en: 'Switch to pump B; check pump A' },
  },
  {
    alarmId: 'WTP-DEMAND-HI',
    tagId: 'WTP_DEMAND_01',
    condition: 'H',
    priority: 'P3',
    setpoint: 180,
    deadband: 5,
    onDelayMs: 5000,
    offDelayMs: 10000,
    consequence: { vi: 'Nhu cầu nước cao', en: 'High water demand' },
  },
  {
    alarmId: 'WTP-OUT-FLOW-HI',
    tagId: 'WTP_OUT_FLOW_01',
    condition: 'H',
    priority: 'P3',
    setpoint: 190,
    deadband: 5,
    onDelayMs: 5000,
    offDelayMs: 10000,
    consequence: { vi: 'Lưu lượng ra cao (nghi rò rỉ)', en: 'High outflow (possible leak)' },
  },
];
